language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

services:
  - redis-server

before_script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then pear config-set preferred_state beta; fi;'
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then yes '' | pecl install apcu; fi;'
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-add install/travis-$TRAVIS_PHP_VERSION.ini; fi;'
  - travis_retry composer self-update
  - composer require satooshi/php-coveralls --prefer-source

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" = "5.5" ]; then php vendor/bin/coveralls -v; fi;'
