sudo: false

language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

matrix:
  allow_failures:
    - php: 7.1

services:
  - redis-server

before_install:
  - if [[ $TRAVIS_PHP_VERSION = "5.5" ]]; then echo yes | pecl install apcu-4.0.11; fi
  - if [[ $TRAVIS_PHP_VERSION = "5.6" ]]; then echo yes | pecl install apcu-4.0.11; fi
  - if [[ $TRAVIS_PHP_VERSION = "7.0" ]]; then echo yes | pecl install apcu-5.1.5; fi
  - if [[ $TRAVIS_PHP_VERSION = "7.1" ]]; then echo yes | pecl install apcu-5.1.5; fi
  - if [[ $TRAVIS_PHP_VERSION != "hhvm" ]]; then phpenv config-add install/travis-$TRAVIS_PHP_VERSION.ini; fi

before_script:
  - if [[ $TRAVIS_PHP_VERSION != "5.5" ]]; then composer install; fi
  - if [[ $TRAVIS_PHP_VERSION = "5.5" ]]; then composer require satooshi/php-coveralls --prefer-source; fi

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - if [[ $TRAVIS_PHP_VERSION = "5.5" ]]; then php vendor/bin/coveralls -v; fi
