sudo: false

cache:
  directories:
    - $COMPOSER_CACHE_DIR
    - $HOME/.composer/cache
    - $TRAVIS_BUILD_DIR/build

language: php

php:
  - 8.1

services:
  - redis-server

before_install:
  - phpenv config-add .travis/php.ini

before_script:
  - if [[ $TRAVIS_PHP_VERSION != "8.1" ]]; then phpenv config-rm xdebug.ini; fi

script:
  - if [[ $TRAVIS_PHP_VERSION == "8.1" ]]; then make test-coveralls; else make test; fi
